version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./db:/var/lib/mysql
     #restart: always
     environment:
       MYSQL_ROOT_PASSWORD: superp@ssw0rd
       MYSQL_DATABASE: wp-shop
       MYSQL_USER: shopuser
       MYSQL_PASSWORD: p@ssw0rd

   wp:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8003:80"
     #restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: superp@ssw0rd
     volumes:
        - ./wp:/var/www/html
volumes:
    db_data: